Repository PawWithU/ConnectDog-Server, pull requests merged in 2024-06, with the labels that each got.

#221 [Feature] 발생되는 이슈 수정
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/IntermediarySignUpRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/service/FcmService.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/entity/Intermediary.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerController.java
  src/main/resources/import.sql
  src/test/java/com/pawwithu/connectdog/domain/auth/controller/SignUpControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#219 [Feature] 봉사자 회원 탈퇴 API 구현
  src/main/java/com/pawwithu/connectdog/domain/application/entity/Application.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/ApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/AuthController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/badge/repository/CustomVolunteerBadgeRepository.java
  src/main/java/com/pawwithu/connectdog/domain/badge/repository/VolunteerBadgeRepository.java
  src/main/java/com/pawwithu/connectdog/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/pawwithu/connectdog/domain/review/entity/Review.java
  src/main/java/com/pawwithu/connectdog/domain/review/repository/ReviewRepository.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/repository/VolunteerRepository.java
  src/main/java/com/pawwithu/connectdog/error/ErrorCode.java
  src/main/resources/import.sql
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#224 [Feature] 모집자, 봉사자 내 정보 관리 및 모집자명 중복 확인 API 구현
  src/main/java/com/pawwithu/connectdog/config/SecurityConfig.java
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/IntermediaryNameRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/IntermediaryNameResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryGetMySettingInfoResponse.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/dto/response/VolunteerGetMySettingInfoResponse.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/service/VolunteerService.java
  src/main/resources/import.sql
  src/test/java/com/pawwithu/connectdog/domain/auth/controller/SignUpControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#226 [Docs] 알림 목록 더미 데이터 추가
  src/main/resources/application.yml
  src/main/resources/import.sql
Labels: 📃 Docs, Priority: Low, 🐯 Koeyhk

#228 [Feature] 이동봉사 신청 시 검증 로직 수정
  src/main/java/com/pawwithu/connectdog/domain/application/entity/Application.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/ApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/CustomApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/impl/CustomApplicationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/application/service/ApplicationService.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/PostRepository.java
Labels: ✨ Feature, Priority: High, 🐯 Koeyhk

#230 [Feature] 이메일 찾기 구현 및 이메일 인증 구현
  src/main/java/com/pawwithu/connectdog/config/SecurityConfig.java
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/IntermediaryEmailResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/VolunteerEmailResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/EmailService.java
  src/test/java/com/pawwithu/connectdog/domain/auth/controller/SignUpControllerTest.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#231 [Feature] 모집자 회원 탈퇴 API 구현
  src/main/java/com/pawwithu/connectdog/domain/application/entity/Application.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/ApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/AuthController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/IntermediaryNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/VolunteerNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/post/entity/Post.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/PostRepository.java
  src/main/resources/import.sql
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#233 [Feature] 봉사자, 모집자 비밀번호 찾기 - 이메일 인증 API 수정
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/AuthController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/IntermediaryEmailWithAuthResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/VolunteerEmailWithAuthResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/EmailService.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#235 [Fix] 공고 삭제 - 반려된 신청이 존재하는 공고도 삭제하도록 구현
  src/main/java/com/pawwithu/connectdog/domain/application/repository/ApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/PostRepository.java
  src/main/java/com/pawwithu/connectdog/domain/post/service/PostService.java
Labels: ⚠ BugFix, Priority: Medium, 🐯 Koeyhk

#237 [Docs] 이메일 전송 템플릿 수정
  src/main/resources/templates/mail.html
Labels: 📃 Docs, Priority: Low, 🐯 Koeyhk

#239 [Feature] 봉사자, 모집자 이메일 중복 가능하도록 변경
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/EmailService.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/entity/Volunteer.java
  src/main/java/com/pawwithu/connectdog/error/ErrorCode.java
  src/test/java/com/pawwithu/connectdog/domain/auth/controller/SignUpControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#241 [Feature] 봉사자, 모집자 신청 내역 단건 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationIntermediaryGetOneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationVolunteerGetOneResponse.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk
