Repository PawWithU/ConnectDog-Server, pull requests merged in 2024-05, with the labels that each got.

#164 [Feature] 이동봉사 모집자 봉사 관리 - 목록 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationIntermediaryCompletedResponse.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationIntermediaryProgressingResponse.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationIntermediaryWaitingResponse.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/impl/CustomApplicationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/dog/entity/DogSize.java
  src/main/java/com/pawwithu/connectdog/domain/post/controller/PostController.java
  src/main/java/com/pawwithu/connectdog/domain/post/dto/response/PostRecruitingGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/post/entity/PostStatus.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/test/java/com/pawwithu/connectdog/domain/application/controller/ApplicationControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/post/controller/PostControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#166 [Feature] 이동봉사자, 모집자 자체 회원가입 API 수정
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/IntermediarySignUpRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/VolunteerSignUpRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/entity/Intermediary.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/repository/IntermediaryRepository.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/entity/Volunteer.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/repository/VolunteerRepository.java
  src/main/java/com/pawwithu/connectdog/error/ErrorCode.java
  src/test/java/com/pawwithu/connectdog/domain/auth/controller/SignUpControllerTest.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#169 [Feature] 이동봉사자, 모집자 휴대폰 번호 중복 검사 API 구현
  src/main/java/com/pawwithu/connectdog/config/SecurityConfig.java
  src/main/java/com/pawwithu/connectdog/domain/auth/controller/SignUpController.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/IntermediaryPhoneRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/VolunteerPhoneRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/IntermediaryPhoneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/response/VolunteerPhoneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/repository/IntermediaryRepository.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/repository/VolunteerRepository.java
  src/main/resources/import.sql
  src/test/java/com/pawwithu/connectdog/domain/auth/controller/SignUpControllerTest.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#170 [Feature] 이동봉사 후기 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryGetReviewsResponse.java
  src/main/java/com/pawwithu/connectdog/domain/review/dto/response/ReviewGetAllResponse.java
  src/main/java/com/pawwithu/connectdog/domain/review/dto/response/ReviewGetOneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/review/repository/impl/CustomReviewRepositoryImpl.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/review/controller/ReviewControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#172 [Feature] 이동봉사자, 모집자 - 모집자 프로필 공고 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryGetPostsResponse.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/CustomPostRepository.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#175 [Feature] 이동봉사 후기 조회 API 추가 수정
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryGetReviewsResponse.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/main/java/com/pawwithu/connectdog/domain/review/dto/response/ReviewGetAllResponse.java
  src/main/java/com/pawwithu/connectdog/domain/review/repository/impl/CustomReviewRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/review/service/ReviewService.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/review/controller/ReviewControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#179 [Feature] 마이페이지 북마크한 공고 목록 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/bookmark/repository/CustomBookmarkRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/dto/response/VolunteerGetMyBookmarkResponse.java
  src/test/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#180 [Feature] 이동봉사 신청 관련 API 수정
  src/main/java/com/pawwithu/connectdog/domain/application/controller/ApplicationController.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/request/VolunteerApplyRequest.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationIntermediaryGetOneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/response/ApplicationVolunteerGetOneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/application/entity/Application.java
  src/main/java/com/pawwithu/connectdog/domain/application/entity/ApplicationStatus.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/CustomApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/impl/CustomApplicationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/application/service/ApplicationService.java
  src/main/resources/import.sql
  src/test/java/com/pawwithu/connectdog/domain/application/controller/ApplicationControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/application/service/ApplicationServiceTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#183 [Feature] 홈 화면 공고 조회, 공고 필터 검색 API 반환값 수정
  src/main/java/com/pawwithu/connectdog/domain/post/dto/response/PostGetHomeResponse.java
  src/main/java/com/pawwithu/connectdog/domain/post/dto/response/PostSearchResponse.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/test/java/com/pawwithu/connectdog/domain/post/controller/PostControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#184 [Feature] 이동봉사자 마이페이지 메인 정보 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/application/repository/CustomApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/impl/CustomApplicationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/dto/response/VolunteerGetMyInfoResponse.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/service/VolunteerService.java
  src/test/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#186 [Feature] 봉사자 공고 관련 API 수정
  src/main/java/com/pawwithu/connectdog/domain/application/controller/ApplicationController.java
  src/main/java/com/pawwithu/connectdog/domain/application/dto/request/VolunteerApplyRequest.java
  src/main/java/com/pawwithu/connectdog/domain/post/controller/PostController.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/CustomPostRepository.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/impl/CustomPostRepositoryImpl.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#188 [Feature] 이동봉사자 모집자 프로필 - 기본 정보 조회 API 수정
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryGetInfoResponse.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#191 [Feature] 모집자 프로필 - 기본 정보 조회 API 구현
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#192 [Feature] 알림 전송 구현 및 알림 목록 조회를 위한 Entity 생성
  src/main/java/com/pawwithu/connectdog/domain/application/service/ApplicationService.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/controller/FcmController.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/dto/NotificationMessage.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/repository/IntermediaryFcmRepository.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/repository/VolunteerFcmRepository.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/service/FcmService.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/IntermediaryNotification.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/VolunteerNotification.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/IntermediaryNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/VolunteerNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/review/service/ReviewService.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#194 알림 Entity NotificationType 필드 추가 및 수정
  src/main/java/com/pawwithu/connectdog/domain/application/controller/ApplicationController.java
  src/main/java/com/pawwithu/connectdog/domain/application/service/ApplicationService.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/controller/FcmController.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/service/FcmService.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/IntermediaryNotification.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/NotificationType.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/VolunteerNotification.java
  src/main/java/com/pawwithu/connectdog/domain/review/service/ReviewService.java
  src/test/java/com/pawwithu/connectdog/domain/application/controller/ApplicationControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#196 [Feature] 봉사자, 모집자 알림 목록 조회 API 구현
  src/main/java/com/pawwithu/connectdog/domain/application/entity/Application.java
  src/main/java/com/pawwithu/connectdog/domain/dog/entity/Dog.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/entity/IntermediaryFcm.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/entity/VolunteerFcm.java
  src/main/java/com/pawwithu/connectdog/domain/notification/controller/NotificationController.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationIntermediaryGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationVolunteerGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/CustomNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/impl/CustomNotificationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/notification/service/NotificationService.java
  src/main/java/com/pawwithu/connectdog/domain/post/entity/Post.java
  src/main/resources/import.sql
  src/test/java/com/pawwithu/connectdog/domain/notification/controller/NotificationControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#201 [Feature] 소셜 추가 회원가입 API 수정
  src/main/java/com/pawwithu/connectdog/domain/auth/dto/request/SocialSignUpRequest.java
  src/main/java/com/pawwithu/connectdog/domain/auth/service/AuthService.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/entity/Volunteer.java
  src/main/resources/import.sql
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong

#203 [Feature] 공고 수정 API 구현
  src/main/java/com/pawwithu/connectdog/domain/dog/entity/Dog.java
  src/main/java/com/pawwithu/connectdog/domain/post/controller/PostController.java
  src/main/java/com/pawwithu/connectdog/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/pawwithu/connectdog/domain/post/entity/Post.java
  src/main/java/com/pawwithu/connectdog/domain/post/service/PostService.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#205 [Feature] 스케줄링 작업 구현
  src/main/java/com/pawwithu/connectdog/domain/application/repository/CustomApplicationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/application/repository/impl/CustomApplicationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/fcm/dto/NotificationMessage.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/NotificationType.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/CustomPostRepository.java
  src/main/java/com/pawwithu/connectdog/domain/post/repository/impl/CustomPostRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/scheduler/SchedulerService.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/repository/CustomVolunteerRepository.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/repository/impl/CustomVolunteerRepositoryImpl.java
  src/main/resources/import.sql
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#207 [Docs] import.sql 쿼리 추가/수정
  src/main/resources/import.sql
Labels: 📃 Docs, Priority: Low, 🐰 Hojeong

#209 [Feature] 스케줄링 기능 활성화
  src/main/java/com/pawwithu/connectdog/ConnectdogApplication.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#211 [Docs] 스케줄링 로그 추가
  src/main/java/com/pawwithu/connectdog/domain/scheduler/SchedulerService.java
Labels: 📃 Docs, Priority: Low, 🐯 Koeyhk

#213 [Feature] 봉사자 모집자 알림 설정 구현
  src/main/java/com/pawwithu/connectdog/domain/fcm/service/FcmService.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryGetNotificationResponse.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/entity/Intermediary.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/dto/response/VolunteerGetNotificationResponse.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/entity/Volunteer.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/service/VolunteerService.java
  src/main/resources/import.sql
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐯 Koeyhk

#215 [Feature] 봉사자 모집자 알림 단건 조회 API 구현
  src/main/java/com/pawwithu/connectdog/domain/notification/controller/NotificationController.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationIntermediaryGetOneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationIntermediaryGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationVolunteerGetOneResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationVolunteerGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationsIntermediaryGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/dto/response/NotificationsVolunteerGetResponse.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/IntermediaryNotification.java
  src/main/java/com/pawwithu/connectdog/domain/notification/entity/VolunteerNotification.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/CustomNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/IntermediaryNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/VolunteerNotificationRepository.java
  src/main/java/com/pawwithu/connectdog/domain/notification/repository/impl/CustomNotificationRepositoryImpl.java
  src/main/java/com/pawwithu/connectdog/domain/notification/service/NotificationService.java
  src/main/java/com/pawwithu/connectdog/error/ErrorCode.java
  src/test/java/com/pawwithu/connectdog/domain/notification/controller/NotificationControllerTest.java
Labels: ✨ Feature, Priority: Low, 🐯 Koeyhk

#217 [Feature] 비밀번호 변경 - 봉사자/모집자 기존 비밀번호 확인 API 구현
  src/main/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryController.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/request/IntermediaryPasswordCheckRequest.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/dto/response/IntermediaryPasswordCheckResponse.java
  src/main/java/com/pawwithu/connectdog/domain/intermediary/service/IntermediaryService.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerController.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/dto/request/VolunteerPasswordCheckRequest.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/dto/response/VolunteerPasswordCheckResponse.java
  src/main/java/com/pawwithu/connectdog/domain/volunteer/service/VolunteerService.java
  src/test/java/com/pawwithu/connectdog/domain/intermediary/controller/IntermediaryControllerTest.java
  src/test/java/com/pawwithu/connectdog/domain/volunteer/controller/VolunteerControllerTest.java
Labels: ✨ Feature, Priority: Medium, 🐰 Hojeong
